# Generated by Django 5.1.1 on 2025-01-26 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rest_period',
            field=models.IntegerField(help_text='Rest period in seconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
